---
- name: Instalar y configurar CoreDNS en contenedor Docker
  hosts: freeipa_servers
  become: true

  vars:
    coredns_config_dir: "/etc/coredns"
    kubeconfig_path: "/etc/coredns/coredns-kubeconfig.yaml"
    k8s_api_vip: "10.17.5.10"
    master1_ip: "10.17.4.21"
    dns_records:
        - { name: "master1", ip: "10.17.4.21" }
        - { name: "master2", ip: "10.17.4.22" }
        - { name: "master3", ip: "10.17.4.23" }
        - { name: "worker1", ip: "10.17.4.24" }
        - { name: "worker2", ip: "10.17.4.25" }
        - { name: "worker3", ip: "10.17.4.26" }
        - { name: "storage1", ip: "10.17.4.27" }
        - { name: "freeipa1", ip: "10.17.3.11" }
        - { name: "loadbalancer1", ip: "10.17.3.12" }
        - { name: "loadbalancer2", ip: "10.17.3.13" }
        - { name: "postgresql1", ip: "10.17.3.14" }
        - { name: "k8s-api-lb", ip: "10.17.5.10" }
        - { name: "k8s-api-lb", ip: "10.17.5.20" }

  tasks:
    # 1. Crear directorios para CoreDNS
    - name: Crear directorios para CoreDNS
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ coredns_config_dir }}"
        - "{{ coredns_config_dir }}/certs"
        - "{{ coredns_config_dir }}/dynamic_conf"

    # 2. Crear archivo de configuraci贸n de CoreDNS
    - name: Crear archivo de configuraci贸n de CoreDNS (Corefile)
      ansible.builtin.template:
        src: templates/Corefile.j2
        dest: "{{ coredns_config_dir }}/Corefile"
        owner: root
        group: root
        mode: '0644'

    # 3. Crear archivo docker-compose.yml
    - name: Generar archivo docker-compose.yml
      ansible.builtin.template:
        src: "templates/docker-compose.yml.j2"
        dest: "{{ coredns_config_dir }}/docker-compose.yml"
        mode: "0644"
      vars:
        vip: "{{ k8s_api_vip }}"

    # 4. Reiniciar contenedor CoreDNS con el nuevo archivo de configuraci贸n
    - name: Reiniciar contenedor CoreDNS con nuevo archivo de configuraci贸n
      shell: |
        docker compose -f {{ coredns_config_dir }}/docker-compose.yml down || true
        docker compose -f {{ coredns_config_dir }}/docker-compose.yml up -d
      args:
        executable: /bin/bash

    # 5. Verificar estado del contenedor CoreDNS
    - name: Verificar estado del contenedor CoreDNS
      shell: docker ps -a | grep coredns || true
      register: coredns_status

    # 6. Mostrar estado del contenedor CoreDNS
    - name: Mostrar estado del contenedor CoreDNS
      debug:
        msg: "{{ coredns_status.stdout_lines }}"