---
- name: Instalar y configurar CoreDNS en contenedor Docker
  hosts: freeipa_servers
  become: true
  gather_facts: yes

  tasks:
    # 1. Actualizar el sistema y todos los paquetes
    - name: Actualizar el sistema y todos los paquetes
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: true

    # 2. Instalar Docker y Docker Compose
    - name: Instalar Docker
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Instalar Docker Compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Iniciar y habilitar Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    # 3. Descargar el archivo de configuración de CoreDNS (Corefile)
    - name: Crear archivo de configuración de CoreDNS (Corefile)
      ansible.builtin.template:
        src: templates/Corefile.j2
        dest: /etc/coredns/Corefile
        owner: root
        group: root
        mode: '0644'

    # 4. Crear un directorio para Docker Compose
    - name: Crear directorio para CoreDNS con Docker Compose
      ansible.builtin.file:
        path: "/etc/coredns/docker"
        state: directory
        mode: '0755'

    # 5. Crear archivo docker-compose.yml para CoreDNS
    - name: Generar archivo docker-compose.yml para CoreDNS
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: /etc/coredns/docker/docker-compose.yml
        mode: '0644'

    # 6. Iniciar el contenedor de CoreDNS con Docker Compose
    - name: Iniciar CoreDNS con Docker Compose
      ansible.builtin.shell: |
        cd /etc/coredns/docker
        docker-compose up -d
      args:
        executable: /bin/bash

    # 7. Verificar el estado del contenedor de CoreDNS
    - name: Verificar el estado del contenedor de CoreDNS
      ansible.builtin.shell: "docker ps | grep coredns || true"
      register: coredns_status

    - name: Mostrar estado del contenedor CoreDNS
      debug:
        msg: "{{ coredns_status.stdout_lines }}"

    # 8. Abrir puertos 53 en firewalld
    - name: Abrir puertos 53 en firewalld
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 53/tcp
        - 53/udp
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
