- name: Instalar y configurar CoreDNS como servidor DNS en AlmaLinux
  hosts: freeipa_servers
  become: true

  vars:
    coredns_version: "1.12.1"
    coredns_dir: "/etc/coredns"
    coredns_bin_path: "/usr/local/bin/coredns"
    resolv_conf_path: "/etc/resolv.conf"
    nameservers:
      - "nameserver 10.17.3.11"
      - "nameserver 8.8.8.8"
    domain_name: "cefaslocalserver.com"
    dns_records:
      - { name: "master1", ip: "10.17.4.21" }
      - { name: "worker1", ip: "10.17.4.24" }

  tasks:
    - name: Instalar dependencias necesarias
      dnf:
        name:
          - curl
          - tar
          - policycoreutils
          - policycoreutils-python-utils
          - selinux-policy
          - selinux-policy-targeted
          - bind-utils    # Se añade bind-utils
          - net-tools     # Se añade net-tools
        state: present

    - name: Crear carpeta para CoreDNS
      file:
        path: "{{ coredns_dir }}"
        state: directory
        mode: '0755'

    - name: Descargar CoreDNS
      get_url:
        url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_linux_amd64.tgz"
        dest: "/tmp/coredns.tgz"

    - name: Extraer y mover CoreDNS a /usr/local/bin
      unarchive:
        src: "/tmp/coredns.tgz"
        dest: "/usr/local/bin/"
        remote_src: yes
        creates: "{{ coredns_bin_path }}"

    - name: Asignar permisos al binario
      file:
        path: "{{ coredns_bin_path }}"
        mode: '0755'

    - name: Crear archivo Corefile
      copy:
        dest: "{{ coredns_dir }}/Corefile"
        content: |
          . {
              hosts {
          {% for record in dns_records %}
                  {{ record.ip }} {{ record.name }}.{{ domain_name }} {{ record.name }}
          {% endfor %}
                  fallthrough
              }
              forward . 8.8.8.8
              log
              errors
          }

    - name: Crear usuario de sistema para CoreDNS
      user:
        name: coredns
        system: yes
        shell: /sbin/nologin
        home: "{{ coredns_dir }}"

    - name: Crear servicio systemd para CoreDNS
      copy:
        dest: /etc/systemd/system/coredns.service
        content: |
          [Unit]
          Description=CoreDNS DNS Server
          After=network.target

          [Service]
          User=coredns
          Group=coredns
          ExecStart={{ coredns_bin_path }} -conf {{ coredns_dir }}/Corefile
          WorkingDirectory={{ coredns_dir }}
          Restart=on-failure
          LimitNOFILE=1048576

          [Install]
          WantedBy=multi-user.target

    - name: Aplicar contexto SELinux al directorio de CoreDNS
      command: semanage fcontext -a -t bin_t "{{ coredns_bin_path }}"
      ignore_errors: true

    - name: Restaurar contexto SELinux
      command: restorecon -Rv "{{ coredns_dir }}"

    - name: Recargar systemd y habilitar servicio
      systemd:
        daemon_reload: yes
        name: coredns
        enabled: yes
        state: started

    - name: Configurar resolv.conf con servidores DNS
      copy:
        dest: "{{ resolv_conf_path }}"
        content: |
          {% for ns in nameservers %}
          {{ ns }}
          {% endfor %}