# CoreDNS_setup.yml
---
- name: Actualizar y configurar CoreDNS en la máquina virtual
  hosts: freeipa_servers
  become: true
  gather_facts: yes

  tasks:
    # 1. Actualizar el sistema
    - name: Actualizar el sistema y todos los paquetes
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: true

    # 2. Instalar CoreDNS desde el repositorio
    - name: Instalar CoreDNS desde repositorio
      ansible.builtin.yum:
        name: coredns
        state: present

    # 3. Crear archivo de configuración CoreDNS (Corefile)
    - name: Crear archivo de configuración de CoreDNS (Corefile)
      ansible.builtin.template:
        src: templates/Corefile.j2
        dest: /etc/coredns/Corefile
        owner: root
        group: root
        mode: '0644'
    
    # 4. Habilitar y arrancar CoreDNS como servicio
    - name: Habilitar y arrancar CoreDNS
      ansible.builtin.systemd:
        name: coredns
        enabled: true
        state: started

    # 5. Verificar el estado de CoreDNS
    - name: Verificar el estado de CoreDNS
      ansible.builtin.systemd:
        name: coredns
        state: started

    # 6. Abrir puertos 53 en firewalld
    - name: Abrir puertos 53 en firewalld
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 53/tcp
        - 53/udp
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded