---
- name: Instalar y configurar CoreDNS en contenedor Docker
  hosts: freeipa_servers
  become: true
  vars:
    coredns_config_dir: "/etc/coredns"
    coredns_token_path: "/mnt/coredns-token/coredns.jwt"
    kubeconfig_path: "/etc/coredns/coredns-kubeconfig.yaml"
    k8s_api_vip: "10.17.5.10"
    master1_ip: "10.17.4.21"

  tasks:
    # 1. Actualizar el sistema
    - name: Actualizar el sistema y todos los paquetes
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: true

    # 2. Instalar Docker
    - name: Instalar Docker
      ansible.builtin.yum:
        name: docker
        state: present

    # 3. Iniciar y habilitar Docker
    - name: Iniciar y habilitar Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    # 4. Instalar Docker Compose
    - name: Instalar Docker Compose
      ansible.builtin.shell: |
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    # 5. Crear directorios para CoreDNS
    - name: Crear directorios para CoreDNS
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ coredns_config_dir }}"
        - "{{ coredns_config_dir }}/certs"
        - "{{ coredns_config_dir }}/dynamic_conf"

    # 6. Crear archivo de configuración de CoreDNS (Corefile)
    - name: Crear archivo de configuración de CoreDNS (Corefile)
      ansible.builtin.template:
        src: templates/Corefile.j2
        dest: "{{ coredns_config_dir }}/Corefile"
        owner: root
        group: root
        mode: '0644'

    # 7. Crear archivo docker-compose.yml
    - name: Generar archivo docker-compose.yml para CoreDNS
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/coredns/docker-compose.yml.j2"
        dest: "{{ coredns_config_dir }}/docker-compose.yml"
        mode: "0644"

    # 8. Ejecutar CoreDNS usando Docker Compose
    - name: Iniciar CoreDNS en Docker con Docker Compose
      shell: |
        docker-compose -f {{ coredns_config_dir }}/docker-compose.yml down || true
        docker-compose -f {{ coredns_config_dir }}/docker-compose.yml up -d
      args:
        executable: /bin/bash

    # 9. Verificar el estado del contenedor CoreDNS
    - name: Verificar estado del contenedor CoreDNS
      shell: docker ps -a | grep coredns || true
      register: coredns_status

    # 10. Mostrar el estado del contenedor CoreDNS
    - name: Mostrar estado del contenedor CoreDNS
      debug:
        msg: "{{ coredns_status.stdout_lines }}"