# CoreDNS_setup.yml
---
- name: Actualizar y configurar CoreDNS en la máquina virtual con Docker
  hosts: freeipa_servers
  become: true
  gather_facts: yes

  tasks:
    # 1. Actualizar el sistema
    - name: Actualizar el sistema y todos los paquetes
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: true

    # 2. Instalar Docker
    - name: Instalar Docker
      ansible.builtin.yum:
        name: docker
        state: present

    # 3. Iniciar y habilitar Docker
    - name: Iniciar y habilitar Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    # 4. Instalar Docker Compose
    - name: Instalar Docker Compose
      ansible.builtin.command:
        cmd: "curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"
        creates: /usr/local/bin/docker-compose

    - name: Establecer permisos de Docker Compose
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: "0755"

    # 5. Descargar e instalar CoreDNS con Docker Compose
    - name: Crear archivo docker-compose.yml para CoreDNS
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: /opt/coredns/docker-compose.yml
        mode: "0644"

    # 6. Iniciar CoreDNS con Docker Compose
    - name: Iniciar CoreDNS con Docker Compose
      ansible.builtin.command:
        cmd: "docker-compose -f /opt/coredns/docker-compose.yml up -d"

    # 7. Verificar el estado de CoreDNS
    - name: Verificar si CoreDNS está corriendo
      ansible.builtin.command:
        cmd: "docker ps -f name=coredns"
      register: coredns_status

    - name: Mostrar estado de CoreDNS
      debug:
        var: coredns_status.stdout

    # 8. Abrir puertos 53 en firewalld
    - name: Abrir puertos 53 en firewalld
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 53/tcp
        - 53/udp
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
